[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/vimproc.vim'
build='make'

[[plugins]]
repo='tpope/vim-commentary'
hook_add="""
  autocmd FileType gp setlocal commentstring=#\ %s
  autocmd FileType m  setlocal commentstring=%\ %s
"""

[[plugins]]
repo='osyo-manga/vim-over'
hook_add="""
  nnoremap <Space>O :OverCommandLine<CR>:%s/
  nnoremap <Space>o :OverCommandLine<CR>
"""

[[plugins]]
repo='sheerun/vim-polyglot'

[[plugins]]
repo='cocopon/iceberg.vim'

[[plugins]]
repo='itchyny/lightline.vim'
hook_add="""
  set noshowmode
  let g:lightline = { \
    'colorscheme': 'iceberg', \
    'active': { \
      'left': [ \
        ['mode',], \
        ['readonly', 'modified',], \
      ], \
      'right': [ \
        ['fileinfo',], \
        ['position',], \
      ], \
    }, \
    'inactive': { \
      'left': [ \
        ['mode',], \
        ['readonly', 'modified',], \
      ], \
      'right': [ \
        ['filename',], \
      ], \
    }, \
    'component': { \
    }, \
    'component_function': { \
      'fileinfo': 'LightlineMyGetFileInfo', \
      'position': 'LightlineMyGetPosition', \
    }, \
  }
  function! LightlineMyGetFileInfo() abort
    let l:filename = expand('%:t')
    let l:filename = l:filename !=# '' ? l:filename : '[No Name]'
    if winwidth(0) > 70
      let l:filetype = &filetype !=# '' ? &filetype : '[No Type]'
      return l:filename . ' | ' . l:filetype
    else
      return l:filename
    endif
  endfunction
  function! LightlineMyGetPosition() abort
    if winwidth(0) > 70
      let l:row = line('.')
      let l:col = col('.')
      let l:byte = line2byte(l:row) + l:col - 1
      return 'R:' . l:row . ' | ' . 'C:' . l:col . ' | ' . 'B:' . l:byte
    else
      return ''
    endif
  endfunction
"""

[[plugins]]
repo='rust-lang/rust.vim'

[[plugins]]
repo='tikhomirov/vim-glsl'

[[plugins]]
repo='prisma/vim-prisma'
