[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/VimProc'
build='make'

[[plugins]]
repo='Shougo/deoplete.nvim'
hook_add="""
  let g:deoplete#enable_at_startup=1
"""

[[plugins]]
repo='scrooloose/nerdtree'
hook_add='''
  nnoremap <Space>n :NERDTree<CR>
'''

[[plugins]]
repo='tomasr/molokai'
hook_add='''
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo='tpope/vim-commentary'

[[plugins]]
repo='Yggdroot/indentLine'

[[plugins]]
repo='osyo-manga/vim-over'
hook_add='''
  nnoremap <Space>o :OverCommandLine<CR>:%s/
'''

[[plugins]]
repo='itchyny/lightline.vim'
hook_add="""
  set noshowmode
  let g:lightline={ \
    'colorscheme': 'default', \
    'active': { \
      'right': [['fileformat'],['totallines', 'filetype', 'fileencoding']] \
    }, \
    'component': { \
      'totallines': '%L lines' \
    }, \
  }
"""
