[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/VimProc'

[[plugins]]
repo='Shougo/VimShell'

[[plugins]]
repo='Shougo/neocomplete.vim'
hook_add='''
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#min_keyword_length = 3
  let g:neocomplete#enable_auto_delimiter = 1
  let g:neocomplete#auto_completion_start_length = 1
  inoremap <expr><BS> neocomplete#smart_close_popup()."<C-h>"
  imap <expr><CR> neosnippet#expandable() ? "<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "<C-y>" : "<CR>"
  imap <expr><TAB> pumvisible() ? "<C-n>" : neosnippet#jumpable() ? "<Plug>(neosnippet_expand_or_jump)" : "<TAB>"
'''

[[plugins]]
repo='Shougo/neosnippet.vim'

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='scrooloose/nerdtree'
hook_add='''
  nnoremap <Space>n :NERDTree<CR>
'''

[[plugins]]
repo='tomasr/molokai'
hook_add='''
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo='tpope/vim-commentary'

[[plugins]]
repo='thinca/vim-quickrun'
hook_add='''
  let g:quickrun_config = {
  \  "_": {
  \    "outputter/buffer/split": ":botright",
  \    "outputter/buffer/close_on_empty": 1
  \  }
  \}
  nnoremap <Space>q :QuickRun<CR>
'''

[[plugins]]
repo='itchyny/lightline.vim'
hook_add='''
  set laststatus=2
  set noshowmode
'''

[[plugins]]
repo='Yggdroot/indentLine'

