[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/VimProc'
build='make'

[[plugins]]
repo='tpope/vim-commentary'

[[plugins]]
repo='osyo-manga/vim-over'
hook_add="""
  nnoremap <Space>O :OverCommandLine<CR>:%s/
  nnoremap <Space>o :OverCommandLine<CR>
"""

[[plugins]]
repo='NaokiHori/iceberg.vim'
hook_add="""
  au MyAutoCmd VimEnter * nested colorscheme iceberg
"""

[[plugins]]
repo='itchyny/lightline.vim'
hook_add="""
  set noshowmode
  let g:lightline={ \
    'colorscheme': 'iceberg', \
    'active': { \
      'right': [['fileformat'],['totallines', 'filetype', 'fileencoding']] \
    }, \
    'component': { \
      'totallines': '%L lines' \
    }, \
  }
"""

