set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set -sg escape-time 0
set-option -g allow-rename off

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g pane-border-bg colour0
set -g pane-border-fg colour255
set -g pane-active-border-bg colour0
set -g pane-active-border-fg colour20

set -g message-fg colour16
set -g message-bg colour3
set -g message-attr bright

set -g status-fg "colour255"
set -g status-bg "colour235"
set -g status-interval 1
set-option -g status-left-length  20
set-option -g status-left  "#[fg=colour255,bg=colour52] Session: #S #[default]"
set-option -g status-right-length 20
set-option -g status-right '#[fg=colour233,bg=colour28,bold] %y-%m-%d #[fg=colour233,bg=colour8,bold] %H:%M:%S '
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I: #W "
