# use Ctrl+a as prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix
# basic settings
set -g base-index 1
setw -g renumber-windows on
set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm:colors=256"
set -g allow-rename off
set -sg escape-time 0
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"
setw -g mode-keys vi
setw -g status-keys vi
#bind-key p paste-buffer
# resize pane key bind
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# pain colour
set -g window-style "fg=colour239,bg=black"
set -g window-active-style "fg=white,bg=black"
# set border colour of pain
set -g pane-border-bg "#000000"
set -g pane-border-fg "#ffffff"
set -g pane-active-border-bg "#000000"
set -g pane-active-border-fg "#0000ff"
# message window settings
set -g message-fg "#cccc00"
set -g message-bg "#000000"
# status line
set -g status-justify left
set -g status-fg "#ffffff"
set -g status-bg "#282828"
set -g status-attr default
set -g status-interval 1
set -g status-left-length 50
set -g status-left " #[bg=#c80000] SES: #(exec echo $((#S+1))) / #(exec tmux ls | wc -l) #[default] "
set -g status-right-length 120
set -g status-right " #[bg=#00a000] DIR: #{b:pane_current_path} #[bg=#008200] #h: #(exec bash ~/dotfiles/.tmux/localip) #[default] #[bg=#006400] TIME: 20%y/%m/%d(%a) %H:%M:%S #[default] "
setw -g window-status-format "#[bg=#000064] #I: #W #[default]"
setw -g window-status-current-format "#[bg=#0000c8,bold]#{?client_prefix,#[reverse],} WIN#I: #W #[default]"
