# use Ctrl+a as prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix
# basic settings
set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm:colors=256"
set -g allow-rename off
set -sg escape-time 0
# buffer
setw -g mode-keys vi
bind-key p paste-buffer
# resize pane key bind
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# pain colour
set -g window-style "fg=colour239,bg=black"
set -g window-active-style "fg=white,bg=black"
# set border colour of pain
set -g pane-border-bg black
set -g pane-border-fg white
set -g pane-active-border-bg colour0
set -g pane-active-border-fg colour20
# message window settings
set -g message-fg colour16
set -g message-bg colour3
set -g message-attr bright
# status line
set -g status-justify left
set -g status-fg "colour255"
set -g status-bg "colour235"
set -g status-interval 1
set -g status-left-length 50
set -g status-left " #[bg=colour124] Session: #S Total: #(exec tmux ls | wc -l) #[default] "
set -g status-right-length 70
set -g status-right " #[bg=colour28,bold] %y-%m-%d(%a) #[bg=colour22,bold] %H:%M:%S #[default] "
setw -g window-status-format "#[bg=colour238] #I: #W #[default]"
setw -g window-status-current-format "#[bg=colour27,bold] #I: #W #[default]"
