#!/bin/bash
if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
  git_info="branch: ${git_branch}"
else
  git_info="no \".git\""
fi

echo "$git_info"
